### ISSUE TITLE
Documentaiton

### ISSUE THREAD

**Issue by SDkie** [arvitaly/go-graphql-schema-generator#1]
Hi @arvitaly :  
Thanks for the amazing tool 👍 
Do you have any blog/documentations how to use it? 
I figured out basic functionality from the example.
But I didn't got few thinks like: 'Why Node is declared as Interface?'

**Comment by arvitaly** [comment]
Hi, @SDkie 
Thanks.
Now i don't have documentation.

> But I didn't got few thinks like: 'Why Node is declared as Interface?'
https://facebook.github.io/relay/graphql/objectidentification.htm#sec-Node-Interface

**Comment by SDkie** [comment]
Okay fine.
Thanks for your response.
